config/routes.rb
Rails.application.routes.draw do
  resources :replies do
    collection { post :import}
  end
  resources :responses
  
end

app/models/reply.rb
class Reply < ActiveRecord::Base
	
serialize :greeting,Array
serialize :line_one,Array
serialize :line_two,Array
serialize :line_three,Array
serialize :line_four,Array
serialize :closing,Array
serialize :salutation,Array


	
end

app/models/response.rb
class Response < ActiveRecord::Base
	belongs_to :replies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_reply, only: [:show, :edit, :update, :destroy]

  # GET /replies
  # GET /replies.json
  def index
    @replies = Reply.all
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
    
  end

  # GET /replies/new
  def new
    @reply = Reply.new
  end

  # GET /replies/1/edit
  def edit
  end

  # POST /replies
  # POST /replies.json
  def create
    @reply = Reply.new(reply_params)

    respond_to do |format|
      if @reply.save
        format.html { redirect_to @reply, notice: 'Reply was successfully created.' }
        format.json { render :show, status: :created, location: @reply }
      else
        format.html { render :new }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /replies/1
  # PATCH/PUT /replies/1.json
  def update
    respond_to do |format|
      if @reply.update(reply_params)
        format.html { redirect_to @reply, notice: 'Reply was successfully updated.' }
        format.json { render :show, status: :ok, location: @reply }
      else
        format.html { render :edit }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @reply.destroy
    respond_to do |format|
      format.html { redirect_to replies_url, notice: 'Reply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reply
      @reply = Reply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reply_params
      params.require(:reply).permit(:greeting, :line_one, :line_two, :line_three, :closing)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/replies/_form.html.erb
<%= form_for(@reply) do |f| %>
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
      <% @reply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :greeting %><br>
    <%= f.text_area :greeting %>
  </div>
  <div class="field">
    <%= f.label :line_one %><br>
    <%= f.text_area :line_one %>
  </div>
  <div class="field">
    <%= f.label :line_two %><br>
    <%= f.text_area :line_two %>
  </div>
  <div class="field">
    <%= f.label :line_three %><br>
    <%= f.text_area :line_three %>
  </div>
  <div class="field">
    <%= f.label :line_four %><br>
    <%= f.text_area :line_four %>
  </div>
  <div class="field">
    <%= f.label :closing %><br>
    <%= f.text_area :closing %>
  </div>
  <div class="field">
    <%= f.label :salutation %><br>
    <%= f.text_area :salutation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/replies/edit.html.erb
<h1>Editing Reply</h1>

<%= render 'form' %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', replies_path %>

app/views/replies/index.html.erb
<p id="notice"><%= notice %></p>

<h1> Replies</h1>


  <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= reply.greeting %></td>
        <td><%= reply.line_one %></td>
        <td><%= reply.line_two %></td>
        <td><%= reply.line_three %></td>
        <td><%= reply.closing %></td>
   
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Response', new_response_path %>

app/views/replies/new.html.erb
<h1>New Reply</h1>

<%= render 'form' %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Greeting:</strong>
  <%= @reply.greeting %>
</p>

<p>
  <strong>Line one:</strong>
  <%= @reply.line_one %>
</p>

<p>
  <strong>Line two:</strong>
  <%= @reply.line_two %>
</p>

<p>
  <strong>Line three:</strong>
  <%= @reply.line_three %>
</p>

<p>
  <strong>Closing:</strong>
  <%= @reply.closing %>
</p>

<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', replies_path %>