config/routes.rb
Rails.application.routes.draw do
  resources :replies do
    collection { post :import}
  end
  resources :responses
  
end

app/models/reply.rb
class Reply < ActiveRecord::Base
	
serialize :greeting,Array
serialize :line_one,Array
serialize :line_two,Array
serialize :line_three,Array
serialize :line_four,Array
serialize :closing,Array
serialize :salutation,Array


	
end

app/models/response.rb
class Response < ActiveRecord::Base
	belongs_to :replies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_reply, only: [:show, :edit, :update, :destroy]

  # GET /replies
  # GET /replies.json
  def index
    @replies = Reply.all
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
    
  end

  # GET /replies/new
  def new
    @reply = Reply.new
  end

  # GET /replies/1/edit
  def edit
  end

  # POST /replies
  # POST /replies.json
  def create
    @reply = Reply.new(reply_params)

    respond_to do |format|
      if @reply.save
        format.html { redirect_to @reply, notice: 'Reply was successfully created.' }
        format.json { render :show, status: :created, location: @reply }
      else
        format.html { render :new }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /replies/1
  # PATCH/PUT /replies/1.json
  def update
    respond_to do |format|
      if @reply.update(reply_params)
        format.html { redirect_to @reply, notice: 'Reply was successfully updated.' }
        format.json { render :show, status: :ok, location: @reply }
      else
        format.html { render :edit }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @reply.destroy
    respond_to do |format|
      format.html { redirect_to replies_url, notice: 'Reply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reply
      @reply = Reply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reply_params
      params.require(:reply).permit(:greeting, :line_one, :line_two, :line_three, :closing)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/_form.html.erb
<%= form_for(@response) do |f| %>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
      <% @response.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :response %><br>
    <%= f.select(:response, options_for_select([["positive", "positive"], ["neutral", "neutral"], ["negative", "negative"]])) %>
  </div>
  <div class="field">
    <%= f.label :platform %><br>
    <%= f.select(:platform, options_for_select([["Twitter", "Twitter"], ["Yelp", "Yelp"], ["Trip Advisor", "Trip Advisor"], ["Google Plus", "Google Plus"], ["Facebook", "Facebook"]])) %>
   
  </div>
  <div class="field">
    <%= f.label :reviewer %><br>
    <%= f.text_field :reviewer %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing Response</h1>

<%= render 'form' %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<h1>Listing Responses</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Response </th>
      <th>Platform</th>
      <th>Reviewer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= response.email %></td>
        <td><%= response.response %></td>
        <td><%= response.platform %></td>
        <td><%= response.reviewer %></td>
        <td><%= link_to 'Show', response %></td>
        <td><%= link_to 'Edit', edit_response_path(response) %></td>
        <td><%= link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Response', new_response_path %>

app/views/responses/new.html.erb
<h1>New Response</h1>

<%= render 'form' %>

<%= link_to 'Back', responses_path %>

app/views/responses/show.html.erb
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Reply Pilot</title>
 <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Reply Pilot</title>
    <!-- Bootstrap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css">
  <link rel="stylesheet" href="css/style.css">
  <!-- Favicon Code -->
  <link rel="apple-touch-icon" sizes="57x57" href="images/apple-touch-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="images/apple-touch-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="images/apple-touch-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="images/apple-touch-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="images/apple-touch-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="images/apple-touch-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="images/apple-touch-icon-180x180.png">
  <link rel="icon" type="image/png" href="images/favicon-32x32.png" sizes="32x32">
  <link rel="icon" type="image/png" href="images/android-chrome-192x192.png" sizes="192x192">
  <link rel="icon" type="image/png" href="images/favicon-96x96.png" sizes="96x96">
  <link rel="icon" type="image/png" href="images/favicon-16x16.png" sizes="16x16">
  <link rel="manifest" href="images/manifest.json">
  <meta name="apple-mobile-web-app-title" content="ReplyCopilot">
  <meta name="application-name" content="ReplyCopilot">
  <meta name="msapplication-TileColor" content="#272e39">
  <meta name="msapplication-TileImage" content="images/mstile-144x144.png">
  <meta name="theme-color" content="#ffffff">
  </head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
          <a class="navbar-brand" href="index.html">
            <img class="visible-xs" alt="Reply Copilot" src="images/logo-icon-blue.svg" height="24">
            <img class="hidden-xs" alt="Reply Copilot" src="images/reply-copilot-logo.svg" height="24">
          </a>
        <ul class="nav navbar-nav">
          <li role="presentation"><a href="about.html">About</a></li>
          <li role="presentation"><a href="#">Resources</a></li>
        </ul>
      </div>
    </nav>


<% if @response.response == "positive" && @response.platform == "Twitter"%>
    <p><%=@positive_int %> <%=@positive_line1%>  <%= @positive_line2%> <%= @positive_line3 %>  <%= @positive_line4 %> <%= @positive_line5 %>  <%= @positive_close %> </p>  

    <% elsif @response.response == "neutral" && @response.platform == "Twitter" %>
      <p><%=@neutral_int %> <%=@neutral_line1%>  <%= @neutral_line2%> <%= @neutral_line3 %>  <%= @neutral_line4 %> <%= @neutral_line5 %>  <%= @neutral_close %> </p> 
   
    <% elsif @response.response == "negative" && @response.platform == "Twitter"%>
      <p><%=@negative_int %> <%=@negative_line1%>  <%= @negative_line2%> <%= @negative_line3 %>  <%= @negative_line4 %> <%= @negative_line5 %>  <%= @negative_close %> </p> 
      
    <% elsif @response.response == "positive" && @response.platform == "Yelp"%>
      <p><%=@positive_int %> <%=@positive_line1%>  <%= @positive_line2%> <%= @positive_line3 %>  <%= @positive_line4 %> <%= @positive_line5 %>  <%= @positive_close %> </p> 
       
    <% elsif @response.response == "neutral" && @response.platform == "Yelp"%> 
          <p><%=@neutral_int %> <%=@neutral_line1%>  <%= @neutral_line2%> <%= @neutral_line3 %>  <%= @neutral_line4 %> <%= @neutral_line5 %>  <%= @neutral_close %> </p> 
         
      <% elsif @response.response == "negative" && @response.platform == "Yelp"%>
      <p><%=@negative_int %> <%=@negative_line1%>  <%= @negative_line2%> <%= @negative_line3 %>  <%= @negative_line4 %> <%= @negative_line5 %>  <%= @negative_close %> </p> 
           
     <% elsif @response.response == "positive" && @response.platform == "Trip Advisor"%>
          <p><%=@positive_int %> <%=@positive_line1%>  <%= @positive_line2%> <%= @positive_line3 %>  <%= @positive_line4 %> <%= @positive_line5 %>  <%= @positive_close %> </p> 
    
 <% elsif @response.response == "neutral" && @response.platform == "Trip Advisor"%>
      <p><%=@neutral_int %> <%=@neutral_line1%>  <%= @neutral_line2%> <%= @neutral_line3 %>  <%= @neutral_line4 %> <%= @neutral_line5 %>  <%= @neutral_close %> </p> 
     
   <% elsif @response.response == "negative" && @response.platform == "Trip Advisor"%>
    <p><%=@negative_int %> <%=@negative_line1%>  <%= @negative_line2%> <%= @negative_line3 %>  <%= @negative_line4 %> <%= @negative_line5 %>  <%= @negative_close %> </p> 
       
 <% elsif @response.response == "positive" && @response.platform == "Google Plus"%>
     <p><%=@positive_int %> <%=@positive_line1%>  <%= @positive_line2%> <%= @positive_line3 %>  <%= @positive_line4 %> <%= @positive_line5 %>  <%= @positive_close %> </p> 
      
      <% elsif @response.response == "neutral" && @response.platform == "Google Plus"%>
       <p><%=@neutral_int %> <%=@neutral_line1%>  <%= @neutral_line2%> <%= @neutral_line3 %>  <%= @neutral_line4 %> <%= @neutral_line5 %>  <%= @neutral_close %> </p> 
     
      <% elsif @response.response == "negative" && @response.platform == "Google Plus"%>
     <p><%=@negative_int %> <%=@negative_line1%>  <%= @negative_line2%> <%= @negative_line3 %>  <%= @negative_line4 %> <%= @negative_line5 %>  <%= @negative_close %> </p> 
     
      <% elsif @response.response == "positive" && @response.platform == "Facebook"%>
           <p><%=@positive_int %> <%=@positive_line1%>  <%= @positive_line2%> <%= @positive_line3 %>  <%= @positive_line4 %> <%= @positive_line5 %>  <%= @positive_close %> </p> 
      
      <% elsif @response.response == "neutral" && @response.platform == "Facebook"%>
      <p><%=@neutral_int %> <%=@neutral_line1%>  <%= @neutral_line2%> <%= @neutral_line3 %>  <%= @neutral_line4 %> <%= @neutral_line5 %>  <%= @neutral_close %> </p> 
       
      <% else @response.response == "negative" && @response.platform == "Facebook"%>
    <p><%=@negative_int %> <%=@negative_line1%>  <%= @negative_line2%> <%= @negative_line3 %>  <%= @negative_line4 %> <%= @negative_line5 %>  <%= @negative_close %> </p> 
      
<% end %>

<footer>
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <p class="text-blue text-left">
            <a href="https://twitter.com/replycopilot" target="_blank">
              <i class="fa fa-lg fa-twitter-square"></i>
            </a>
            <a href="https://www.facebook.com/replycopilot" target="_blank">
              <i class="fa fa-lg fa-facebook-square"></i>
            </a>
          </p>
        </div>
        <div class="col-sm-6">
          <p class="text-black text-right">Terms of Service</p>
        </div>
      </div>
    </div>
  </footer>

<%= link_to "Don't Like This? Generate a New Response!", new_response_path %> 
</body>
<script src="js/bootstrap.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/npm.js"></script>
</html>


  